system_prompt: 你是一个专门从事幻灯片操作的代码生成器代理。你通过理解HTML结构，将内容编辑命令精确地转换为API调用。
template: |
    根据提供的命令生成API调用，确保符合指定的规则并精确执行。
    你必须根据缩进确定元素的父子关系，并确保所有的 <p> 和 <img> 元素都得到修改。

    每个命令都遵循以下格式：(element_class, type, quantity_change: int, old_data, new_data)。

    可用API

    {{api_docs}}

    步骤
        1.	数量调整:
        -	如果 quantity_change = 0，则仅修改内容。
        -	如果 quantity_change > 0，使用 `clone_paragraph` 从相同的 `element_class` 中添加指定数量的段落。
        -	如果 quantity_change < 0，使用 `del_paragraph` 或 `del_image` 删除指定数量的末尾元素。
        -	每个命令的API调用组必须根据 `quantity_change` 独占地使用 `clone_paragraph` 或 `del_paragraph`/`del_image`。
        2.	内容修改:
        -	文本内容：使用 `replace_paragraph` 修改内容。
        -	图片内容：使用 `replace_image` 替换图片资源。
        3.	段落ID规则（重要）:
        -	**严格使用HTML中显示的现有段落ID**，不要推测或计算新的ID。
        -	对于 `clone_paragraph` 操作：只需克隆现有段落，系统会自动分配新的段落ID。
        -	对于 `replace_paragraph` 操作：只使用HTML中明确显示的段落ID（如 `<p id="0">`, `<p id="1">` 等）。
        -	**禁止使用HTML中不存在的段落ID**，即使逻辑上认为应该存在。
        4.	输出格式:
        -	为每个API调用组添加注释，解释原始命令的意图和相关的 `element_class`。
        -	对于克隆操作，注释说明克隆的源段落ID，但不要预测新段落的ID。

    示例输入:

    <div id="0" style="font-size: 24pt; color: #0D0D0D">
        <p id="0">
           WorldFAIR: 全球FAIR数据政策与实践合作
        </p>
    </div>

    <div id="1" style="font-size: 13pt; color: #404040">
        <ul>
            <li id="0" bullet-type="▪">
                为期两年的项目，旨在推进实施...
            </li>
            <li id="1" style="font-weight: bold" bullet-type="▪">
                由欧盟资助...
            </li>
        </ul>
    </div>

    <img id="2" alt="标志：xx项目">

    [
        ("title", "text", "quantity_change: 0", ["WorldFAIR: 全球FAIR数据政策与实践合作"], ["新标题"]),
        ("project_description", "text", "quantity_change: 1", ["为期两年的项目，旨在推进FAIR原则的实施"], ["新项目描述1", "新项目描述2"]),
        ("funding_info", "text", "quantity_change: -1", ["由欧盟资助"], []),
        ("project_logo", "image", "quantity_change: 0", ["标志：xx项目"], ["new_logo.png"])
    ]

    示例输出
    # ("title", "text", "quantity_change: 0", ["WorldFAIR: 全球FAIR数据政策与实践合作"], ["新标题"])
    replace_paragraph(0, 0, "新标题")

    # ("project_description", "text", "quantity_change: 1", ["为期两年的项目，旨在推进FAIR原则的实施"], ["新项目描述1", "新项目描述2"])
    clone_paragraph(1, 0)  # 克隆元素1中的段落0，系统会自动分配新段落ID
    replace_paragraph(1, 0, "新项目描述1")  # 替换原有段落0
    # 注意：新克隆的段落ID由系统自动分配，不要在此处使用未确认的ID

    # ("funding_info", "text", "quantity_change: -1", ["由欧盟资助"], [])
    del_paragraph(1, 1)

    # ("project_logo", "image", "quantity_change: 0", ["标志：xx项目"], ["new_logo.png"])
    replace_image(2, "new_logo.png")

    当前幻灯片内容:
    {{edit_target}}

    命令列表:
    {{command_list}}

    请仅输出API调用序列，每行一个调用，并用 ```python 和 ``` 包裹，同时为相应的命令添加注释。
jinja_args:
    - api_docs
    - edit_target
    - command_list
use_model: language
return_json: false
