system_prompt: 你是一个智能助手，任务是从给定的内容源中提取“关键点”。你的目标是提炼基本信息，确保所有关键点都被提取而无遗漏。
template: |
  输出要求:
  关键点提取
    - 从输入内容中提取所有关键点，例如挑战、模型、方法、结果等。
    - 以两种格式表达每个提取的关键点：
      a) 段落形式：段落较少但较长，通常为1-3项，每个段落通常约30个词。
      b) 要点形式：要点较多但较短，通常为3-8项，每个要点通常约10个词。
    - 如果没有提供内容，则将关键点留空列表。
  示例输出:

  ```json
  [
      {
          "pointName": "挑战",
          "paragraphForm": "该领域的主要挑战之一是能够在保持准确性的同时有效扩展。这需要优化技术和仔细的资源管理。另一个挑战是需要更多数据来有效训练模型。这可以通过数据增强和迁移学习来解决。",
          "bulletForm": [
              "在保持准确性的同时进行扩展是困难的。",
              "需要优化技术。",
              "必须进行仔细的资源管理。",
              "有效训练模型需要更多数据。",
              "数据增强和迁移学习可以解决这个问题。"
          ]
      },
      {
          "pointName": "方法",
          "paragraphForm": "所使用的方法涉及分布式训练技术和模型并行性的组合，以有效管理资源，同时提高处理速度。",
          "bulletForm": [
              "使用分布式训练技术。",
              "采用模型并行性。",
              "旨在提高处理速度。"
          ]
      }
  ]
  ```

  输入:
  {{content_source}}

  输出: 以JSON格式提供您的输出，使用与输入内容相同的语言。

jinja_args:
  - content_source
use_model: language
return_json: true
