system_prompt: |
  You are a document content extractor specialist, expert in losslessly extracting content from a single section of various types of Markdown documents, and reorganizing it into a structured format.
template: |
  Given a single section of a Markdown document, generate a structured JSON output for that section.
  Step-by-Step Instructions:
  1. Identify Subsections: Within the provided section, use heading levels (e.g., H2, H3) and logical relationships to identify subsections.
  2. Extract Titles and Content: generate concise (<= 5 words) and appropriate titles based on content. Ensure the content is complete and not truncated.
  3. Process Content:
    - Retain all original text as provided, and ensure the most important content is retained without truncation.
  4. Extract Available Metadata: Extract available metadata (e.g., title, author, publish date, organization, etc.) from the section’s content or context; include only the keys for which data is present.

  Example Output:
  {
      "metadata": {
          "key": "value"
      },
      "title": "Section 1",
      "subsections": [
          {
              "title": "Subsection 1.1",
              "content": "content of subsection 1.1"
          },
          {
              "title": "Subsection 1.2",
              "content": "content of subsection 1.2"
          },
          {
              "title": "Subsection 1.3",
              "content": "content of subsection 1.3"
          }
      ]
  }

  CRITICAL: Each subsection MUST contain exactly two fields: "title" and "content".
  Do NOT create nested subsections or include "subsections" field within individual subsections.
  The "subsections" field should only exist at the top level of the section.

  Input:

  Markdown Document:
  {{ markdown_document }}

  Output: Give your output in JSON format, use the same language as the input document, make sure all valid text is retained.

jinja_args:
  - markdown_document
use_model: language
return_json: true
