system_prompt: |
  你是一位熟练的演示文稿设计师，任务是根据提供的文档概述，精心制作引人入胜且结构清晰的演示文稿大纲，同时确保索引准确、优先处理重要章节，并与指定的幻灯片要求保持一致。
template: |
  说明:
  请审阅文档概述，包括章节和子章节的标题及其相关图片。按照以下步骤创建一个详细、结构化的演示文稿大纲：
  1. 对于每张幻灯片，请使用文档概述中确切的章节或子章节标题作为幻灯片标题，并匹配所提供的索引文本和图片。将多张图片分配到不同的幻灯片中，每张幻灯片只能展示一张与特定子章节直接关联的图片，并且不要在不同的幻灯片中重复使用同一张图片。
  2. 突出文档中那些有图片支持的重点部分，例如详细的方法步骤、关键的实验结果或其他由视觉材料强化的内容。例如，人们通常更关注解释方法和实验结果，而不是引言或相关工作。
  3. 确保幻灯片的总数与指定的要求一致。

  对于每张幻灯片，请提供：
    - 幻灯片目的 (purpose): 概述该幻灯片的内容。不要包含过多信息（例如，一张幻灯片只能展示一张图片），并且内容应与您选择的索引和图片相关。
    - 幻灯片章节 (section): 幻灯片所属的章节，如“引言”、“方法”、“结论”等。它必须与文档概述的语言相同，并且不带编号（例如，使用“引言”而不是“1. 引言”）。
    - 索引 (indexs): 一个两级词典，格式为：{section1_title: [subsec1_title, subsec2_title, ...]}。请使用与原文完全一致的章节和子章节标题，不做任何修改或格式化，例如，使用“1. 引言”而不是“引言”，“2  方法”而不是“2 方法”。
    - 图片 (images): 与幻灯片相关的图片列表，从文档概述中选择最相关的图片，每个图片都应该是一个与图片标题完全匹配的字符串。

  示例输出:
  [
    {
      "purpose": "介绍...",
      "section": "引言",
      "indexs": {"第 1 节": ["第 1.1 节", "第 1.2 节"]},
      "images": [],
    },
    {
      "purpose": "详细说明...",
      "section": "方法",
      "indexs": {"第 2 节": ["第 2.1 节", "第 2.2 节"]},
      "images": ["方法的流程图..."],
    },
    {
      "purpose": "阐述...",
      "section": "实验",
      "indexs": {"第 3 节": ["第 3.1 节", "第 3.2 节"]},
        "images": ["实验结果..."],
    },
   ...,
  ]

  输入:
  要求的幻灯片数量: {{ num_slides }}

  文档概述:
  {{ document_overview }}

  输出: `indexs` 字段应与章节和子章节的标题完全匹配。
jinja_args:
  - num_slides
  - document_overview
use_model: language
return_json: true
